### PR TITLE
Location Text Searching

### PR DESCRIPTION
**Pull request by mhayes853**
This PR simply includes a function which calls out to Amplify Geo under the hood to perform text based location searches. There is some significant handling that needed to be performed to parse the response from amplify geo which is handled in a separate utility function that even has its own set of tests.

### CODE REVIEW

**Review by ZoroarkZark — APPROVED** [review]

**Comment by seanim0920** [comment]
A lot of these diffs are due to the new backend updates, not sure if it will conflict with Tristans PR

**Comment by seanim0920** [comment]
We should their PR merged first so this one will be easier to parse, I think they'll still need to rebase off development

**Comment by seanim0920** [comment]
Alternatively you could discard all of the backend changes besides the ones relating to amplify geo

**Comment by mhayes853** [comment]
Going to close this and reopen with some changes to the `Placemark` type, since the code here is essentially a better version of a normal geocoder.

**Pull request closed without merging**
